### ISSUE TITLE
Workflow update for Alfred v4

### ISSUE THREAD

**Issue by ioemilio** [shawnrice/alfred-2-caffeinate-workflow#15]
The workflow does not work on Alfred v4. It is probably just a matter of updating some paths in the library.sh file, but I did not manage to make it work

**Comment by PaulRenauld** [comment]
It worked right away for me with Alfred 4 and MacOS Mojave without modifying anything, except for the configuration with `caff c`. What issue do you have with it? 
Verify that caffeinate is install in your terminal with `which caffeinate`. For me, it was installed in `/usr/bin/caffeinate`.

**Comment by ioemilio** [comment]
Yep. I have `caffeinate` installed right there.

I looked a bit into the code (`library.sh`) and I think the problem is that the workflow tries to load/store data in the `alfred_workflow_data` variable which is set to `~/Library/Application Support/Alfred 3/Workflow Data/` if Alfred 3 found in `/Applications` folder, and to similar paths for older version of Alfred.
Similar thing for `alfred_workflow_cache` variable.

The code, though, does not seem to support Alfred 4 ("Alfred 4" is not harcoded in the file!). Moreover the new version of Alfred (v4) just creates the folder `~/Library/Application Support/Alfred/` (with no reference to the version). 

However just modifying that portion of code does not seem to work (I did not go much deeper in understanding why).

**Comment by shawnrice** [comment]
I actually looked into it and didn't find anything that would be wrong there. The code you're referring to (https://github.com/shawnrice/alfred-2-caffeinate-workflow/blob/master/library.sh#L133-L150) is mostly compatibility code for earlier versions of Alfred 3 / 2 before that env variable was set. 

In Alfred 4, the `alfred_workflow_directory` variable shouldn't be empty, so that code block shouldn't be executed.

Can you tell me better how it's breaking? Is it throwing errors, or is it just not staying awake? 

One perhaps less than intuitive part of the workflow is that you need to configure it first. The default will make it look like it's not working insofar as it'll keep the system from sleeping, but the display will still sleep. The configuration just changes what command line args to send to caffeinate.

**Comment by ioemilio** [comment]
You are right guys. I think I was just wrong with the configuration and it looks like it is working now.

Thank you!
